name: autofix.ci
on:
  pull_request:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Setup
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Build Readme
        run: pnpm run build:readme

      - name: Fix Lint
        run: |
          pnpm run lint:fix

      - name: Lint Website
        # We run the list twice to ensure that autofix works correctly
        run: |
          cd website
          pnpm i
          pnpm run lint:fix
          pnpm run lint:fix

      - name: Build Again
        run: pnpm run build

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
