name: 'code coverage'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Setup
        run: |
          npm install
          npm run build
      - name: Run Coverage
        run: npm run coverage
      - name: Publish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
      - name: Publish Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
