name: 'code coverage'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Setup
        run: |
          pnpm install
          pnpm run build
      - name: Run Coverage
        run: pnpm run coverage
      - name: Publish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
      - name: Publish Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
