name: lint
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branch:
      - master

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npx cspell "**/{*.ts,*.md}"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm i
      - run: npm run lint
