name: lint
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx cspell . --no-progress

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pnpm i
          pnpm run build
      - run: pnpm run lint
      - name: Lint Website
        run: |
          cd website
          pnpm i
          pnpm run lint
