name: lint
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx cspell "**/{*.ts,*.md}"
    - run: npm run lint

  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm run lint
