on:
  push:
    branches:
      - main
name: release-please

permissions:
  actions: read
  checks: write
  contents: write
  issues: read
  packages: write
  pull-requests: write
  repository-projects: read
  statuses: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

  publish:
    needs: release-please
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish.yml
    with:
      tag: ${{ needs.release-please.outputs.tag }}
    secrets:
      PUBLISH_NPM: ${{ secrets.PUBLISH_NPM }}
    if: ${{ needs.release-please.outputs.release_created }}
