name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  test-os: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: npm install
      - run: npm run test-js
      - run: npm run test-ts
      - run: npm run coverage

  test-legacy-node: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 12.x]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: npm install
      - run: npm run test-js
      - run: npm run test-ts
