name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  test: # make sure build/ci work properly
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - run: node -v
    - run: npm install
    - run: npm run test-js
    - run: npm run test-ts
    - run: npm run coverage

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run coverage
    - name: Publish Coveralls
      if: ${{ github.event_name == 'pull_request' }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
    - name: Publish Codecov
      if: ${{ github.event_name == 'pull_request' }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
