name: 'test-terminate'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node-versions: # make sure build/ci work properly
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x, 22.x, 24.x]
        include:
          - os: windows-latest
            node-version: 24.x
          - os: macos-latest
            node-version: 24.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: node workerTerminate.mjs
