name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: node -v
    - run: npm install
    - run: npm test
    - run: npm test-js
    - run: npm test-ts
